// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayEffectTypes.h"
#include "MKHAbilityTypes.generated.h"

class AMKHProjectileBase;
class AActor;
class UStaticMesh;
class UGameplayEffect;
class UAbilitySystemComponent;

/**
 * Custom gameplay effect context used by Arena to transport extended effect metadata.
 * This context is allocated by UMKHAbilitySystemGlobals and replicated over the network.
 */
USTRUCT()
struct FMKHGameplayEffectContext : public FGameplayEffectContext
{
	GENERATED_BODY()

	/** Returns true when the originating damage roll was marked as critical. */
	bool IsCriticalHit() const { return bCriticalHit; }

	/** Sets whether the originating damage roll should be treated as critical. */
	void SetIsCriticalHit(bool bInIsCriticalHit) { bCriticalHit = bInIsCriticalHit; }

	/** Safely resolves this custom context from a generic gameplay effect context handle. */
	static MAKHIA_API
	FMKHGameplayEffectContext* GetEffectContext(FGameplayEffectContextHandle Handle);

	/** Returns the script struct required by GAS for polymorphic context serialization. */
	virtual UScriptStruct* GetScriptStruct() const override { return FMKHGameplayEffectContext::StaticStruct(); }

	/** Creates a deep copy of this context and preserves optional hit result data. */
	virtual FMKHGameplayEffectContext* Duplicate() const override
	{
		FMKHGameplayEffectContext* NewContext = new FMKHGameplayEffectContext();
		*NewContext = *this;

		if (GetHitResult())
		{
			NewContext->AddHitResult(*GetHitResult(), true);
		}

		return NewContext;
	}

	/** Serializes custom context data for replication and prediction rollback. */
	virtual bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess) override;

private:

	/** Replicated flag indicating whether the effect was generated by a critical hit. */
	UPROPERTY()
	bool bCriticalHit = false;

};

/** Enables copy and custom network serialization support for FMKHGameplayEffectContext. */
template<>
struct TStructOpsTypeTraits<FMKHGameplayEffectContext> : public TStructOpsTypeTraitsBase2<FMKHGameplayEffectContext>
{
	enum
	{
		WithNetSerializer = true,
		WithCopy = true,
	};
};

/** Projectile spawn and movement settings consumed by projectile-based abilities. */
USTRUCT(BlueprintType)
struct FProjectileParams
{
	GENERATED_BODY()

	/** Projectile actor class to spawn when the ability triggers. */
	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<AMKHProjectileBase> ProjectileClass;

	/** Optional static mesh override used by projectile visuals. */
	UPROPERTY(EditDefaultsOnly)
	TObjectPtr<UStaticMesh> ProjectileMesh;

	/** Initial projectile speed in Unreal units per second. */
	UPROPERTY(EditDefaultsOnly)
	float InitialSpeed = 1000.f;

	/** Gravity scale applied by the projectile movement component. */
	UPROPERTY(EditDefaultsOnly)
	float GravityScale = 1.f;

	/** Enables bounce behavior on blocking hit events when true. */
	UPROPERTY(EditDefaultsOnly)
	bool bShouldBounce = false;

	/** Coefficient used to compute rebound velocity when bouncing is enabled. */
	UPROPERTY(EditDefaultsOnly)
	float Bounciness = 0.6f;
};

/** Runtime payload used to build and apply damage gameplay effects. */
USTRUCT(BlueprintType)
struct FDamageEffectInfo
{
	GENERATED_BODY()

	/** Damage calculated from base weapon damage multiplied by ability and runtime modifiers. */
	UPROPERTY(BlueprintReadWrite)
	float BaseDamage = 0.f;

	/** Avatar actor responsible for the effect application flow. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<AActor> AvatarActor = nullptr;

	/** Gameplay effect class used to apply computed damage to the target. */
	UPROPERTY(BlueprintReadWrite)
	TSubclassOf<UGameplayEffect> DamageEffect = nullptr;

	/** Source ability system component that applies the outgoing effect. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<UAbilitySystemComponent> SourceASC = nullptr;

	/** Target ability system component receiving the outgoing effect. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<UAbilitySystemComponent> TargetASC = nullptr;

	//UPROPERTY(BlueprintReadWrite)
	//TSubclassOf<UDamageType> DamageTypeClass;
};
