// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayEffectTypes.h"
#include "Abilities/GameplayAbilityTargetTypes.h"
#include "Equipment/EquipmentTypes.h"
#include "MKHAbilityTypes.generated.h"

class AMKHProjectileBase;
class AActor;
class UStaticMesh;
class UGameplayEffect;
class UAbilitySystemComponent;

/**
 * Custom gameplay effect context used by Makhia to transport extended effect metadata
 * (critical hit flag, on-hit status effects, dodge flag).
 * This context is allocated by UMKHAbilitySystemGlobals and replicated over the network.
 */
USTRUCT()
struct FMKHGameplayEffectContext : public FGameplayEffectContext
{
	GENERATED_BODY()

// ============================================================
// Public Interface
// ============================================================

	/** Returns true when the originating damage roll was marked as critical. */
	bool IsCriticalHit() const { return bCriticalHit; }

	/** Sets whether the originating damage roll should be treated as critical. */
	void SetIsCriticalHit(bool bInIsCriticalHit) { bCriticalHit = bInIsCriticalHit; }

	/** Returns true when the target dodged the attack (perfect dodge, no damage applied). */
	bool IsDodged() const { return bDodged; }

	/** Marks the attack as dodged. Consumed server-side by UMKHAttributeSet; not replicated. */
	void SetIsDodged(bool bInIsDodged) { bDodged = bInIsDodged; }

	/** Retrieves the status effects to apply to the hit target on a successful hit. */
	const TArray<FStatusEffectData>& GetTargetStatusEffects() const { return TargetStatusEffects; }

	/** Stores the status effects to apply to the hit target on a successful hit. */
	void SetTargetStatusEffects(const TArray<FStatusEffectData>& InStatusEffects) { TargetStatusEffects = InStatusEffects; }

	/** Retrieves the status effects to apply back to the attacker on a successful hit. */
	const TArray<FStatusEffectData>& GetSelfOnHitStatusEffects() const { return SelfOnHitStatusEffects; }

	/** Stores the status effects to apply back to the attacker on a successful hit. */
	void SetSelfOnHitStatusEffects(const TArray<FStatusEffectData>& InStatusEffects) { SelfOnHitStatusEffects = InStatusEffects; }

	/** Safely resolves this custom context from a generic gameplay effect context handle. */
	static MAKHIA_API
	FMKHGameplayEffectContext* GetEffectContext(FGameplayEffectContextHandle Handle);

	/** Returns the script struct required by GAS for polymorphic context serialization. */
	virtual UScriptStruct* GetScriptStruct() const override { return FMKHGameplayEffectContext::StaticStruct(); }

// ============================================================
// Protected / Internal Logic
// ============================================================

	/** Creates a deep copy of this context and preserves optional hit result data. */
	virtual FMKHGameplayEffectContext* Duplicate() const override
	{
		FMKHGameplayEffectContext* NewContext = new FMKHGameplayEffectContext();
		*NewContext = *this;

		if (GetHitResult())
		{
			NewContext->AddHitResult(*GetHitResult(), true);
		}

		return NewContext;
	}

	/** Serializes custom context data for replication and prediction rollback. */
	virtual bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess) override;

// ============================================================
// Properties
// ============================================================

private:

	/** Replicated flag indicating whether the effect was generated by a critical hit. */
	UPROPERTY()
	bool bCriticalHit = false;

	/**
	 * Flag set by ExecCalc_Damage when the target dodged the attack. Consumed by
	 * UMKHAttributeSet::PostGameplayEffectExecute on the server in the same frame,
	 * so it is intentionally excluded from NetSerialize.
	 */
	UPROPERTY(NotReplicated)
	bool bDodged = false;

	/** Secondary gameplay effects applied to the hit target when the main effect results in a successful hit. */
	UPROPERTY()
	TArray<FStatusEffectData> TargetStatusEffects;

	/** Secondary gameplay effects applied back to the attacker when the main effect results in a successful hit. */
	UPROPERTY()
	TArray<FStatusEffectData> SelfOnHitStatusEffects;

};

/** Enables copy and custom network serialization support for FMKHGameplayEffectContext. */
template<>
struct TStructOpsTypeTraits<FMKHGameplayEffectContext> : public TStructOpsTypeTraitsBase2<FMKHGameplayEffectContext>
{
	enum
	{
		WithNetSerializer = true,
		WithCopy = true,
	};
};

/**
 * Target data describing a single melee hit detected on the locally-controlled machine.
 *
 * Melee hit detection runs where the attack animation is authoritative for the player
 * experience (the owning client for players, the server for AI). Each detected hit is
 * shipped to the server through the GAS replicated target data pipeline; the server
 * validates plausibility (range, cone, re-hit throttling) before applying damage.
 * ComboIndex travels with the hit so the server prices the strike with the same combo
 * step the client actually performed, even when its own combo bookkeeping lags behind.
 */
USTRUCT(BlueprintType)
struct FMKHGameplayAbilityTargetData_MeleeHit : public FGameplayAbilityTargetData_SingleTargetHit
{
	GENERATED_BODY()

// ============================================================
// Public Interface
// ============================================================

	FMKHGameplayAbilityTargetData_MeleeHit() = default;

	/**
	 * Builds melee hit target data from a detected hit and the combo step that produced it.
	 *
	 * @param InHitResult   The hit detected by the weapon scan.
	 * @param InComboIndex  Sequential combo strike index active when the hit was detected.
	 */
	FMKHGameplayAbilityTargetData_MeleeHit(const FHitResult& InHitResult, int32 InComboIndex)
		: FGameplayAbilityTargetData_SingleTargetHit(InHitResult)
		, ComboIndex(InComboIndex)
	{
	}

	/** Returns the script struct required by GAS for polymorphic target data serialization. */
	virtual UScriptStruct* GetScriptStruct() const override { return FMKHGameplayAbilityTargetData_MeleeHit::StaticStruct(); }

	/** Serializes the base hit result plus the combo strike index. */
	bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess);

// ============================================================
// Properties
// ============================================================

	/** Sequential combo strike index active on the sending machine when the hit was detected. */
	UPROPERTY()
	int32 ComboIndex = 0;
};

/** Enables custom network serialization support for FMKHGameplayAbilityTargetData_MeleeHit. */
template<>
struct TStructOpsTypeTraits<FMKHGameplayAbilityTargetData_MeleeHit> : public TStructOpsTypeTraitsBase2<FMKHGameplayAbilityTargetData_MeleeHit>
{
	enum
	{
		WithNetSerializer = true,
	};
};

/** Projectile spawn and movement settings consumed by projectile-based abilities. */
USTRUCT(BlueprintType)
struct FProjectileParams
{
	GENERATED_BODY()

// ============================================================
// Properties
// ============================================================

	/** Projectile actor class to spawn when the ability triggers. */
	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<AMKHProjectileBase> ProjectileClass;

	/** Optional static mesh override used by projectile visuals. */
	UPROPERTY(EditDefaultsOnly)
	TObjectPtr<UStaticMesh> ProjectileMesh;

	/** Initial projectile speed in Unreal units per second. */
	UPROPERTY(EditDefaultsOnly)
	float InitialSpeed = 1000.f;

	/** Gravity scale applied by the projectile movement component. */
	UPROPERTY(EditDefaultsOnly)
	float GravityScale = 1.f;

	/** Enables bounce behavior on blocking hit events when true. */
	UPROPERTY(EditDefaultsOnly)
	bool bShouldBounce = false;

	/** Coefficient used to compute rebound velocity when bouncing is enabled. */
	UPROPERTY(EditDefaultsOnly)
	float Bounciness = 0.6f;
};

/** Runtime payload used to build and apply damage gameplay effects. */
USTRUCT(BlueprintType)
struct FDamageEffectInfo
{
	GENERATED_BODY()

// ============================================================
// Properties
// ============================================================

	/**
	 * Damage multiplier of the attack (e.g. 1.5 for a heavy attack). The weapon's base
	 * damage is resolved by UExecCalc_Damage at execution time, not carried here.
	 */
	UPROPERTY(BlueprintReadWrite)
	float DamageMultiplier = 1.f;

	/** Stamina Damage to deal when the target is blocking. */
	UPROPERTY(BlueprintReadWrite)
	float StaminaDamage = 0.f;
	
	/** Avatar actor responsible for the effect application flow. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<AActor> AvatarActor = nullptr;

	/** Gameplay effect class used to apply computed damage to the target. */
	UPROPERTY(BlueprintReadWrite)
	TSubclassOf<UGameplayEffect> DamageEffect = nullptr;
		
	/** Status effects applied to the hit target when the attack lands. */
	UPROPERTY(BlueprintReadWrite)
	TArray<FStatusEffectData> TargetStatusEffects;

	/** Status effects applied back to the attacker when the attack lands. */
	UPROPERTY(BlueprintReadWrite)
	TArray<FStatusEffectData> SelfOnHitStatusEffects;

	/** Source ability system component that applies the outgoing effect. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<UAbilitySystemComponent> SourceASC = nullptr;

	/** Target ability system component receiving the outgoing effect. */
	UPROPERTY(BlueprintReadWrite)
	TObjectPtr<UAbilitySystemComponent> TargetASC = nullptr;

};
