// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameplayTagContainer.h"
#include "ItemTypes.h"
#include "Delegates/DelegateCombinations.h"
#include "Equipment/EquipmentTypes.h"
#include "Net/Serialization/FastArraySerializer.h"
#include "InventoryComponent.generated.h"

class UInventoryItem;
class UInventoryComponent;
class UItemTypesToTables;
class UEquipmentStatEffects;
struct FStreamableHandle;
struct FStreamableManager;

DECLARE_MULTICAST_DELEGATE_OneParam(FEquipmentItemUsed, UInventoryItem* /*Inventory Item*/);
DECLARE_MULTICAST_DELEGATE_OneParam(FEquipmentItemUnequipped, int64 /*ItemIDToRemove*/);

USTRUCT(BlueprintType)
struct FRPGInventoryEntry : public FFastArraySerializerItem
{
	GENERATED_BODY()

	/** Gameplay tag that identifies the item definition. */
	UPROPERTY(BlueprintReadOnly)
	FGameplayTag ItemTag = FGameplayTag();

	/** Localized display name shown in UI. */
	UPROPERTY(BlueprintReadOnly)
	FText ItemName = FText();

	/** Current stack quantity. */
	UPROPERTY(BlueprintReadOnly)
	int32 Quantity = 0;

	/** Unique item identifier generated by the inventory list. */
	UPROPERTY(BlueprintReadOnly)
	int64 ItemID = 0;

	/** Rolled stat effects and abilities associated with this item. */
	UPROPERTY(BlueprintReadOnly)
	FEquipmentEffectPackage EffectPackage = FEquipmentEffectPackage();

	/** Rarity tag of the item. */
	UPROPERTY(BlueprintReadOnly)
	FGameplayTag RarityTag = FGameplayTag();

	/** True when the item is currently assigned to a quick slot. */
	UPROPERTY(BlueprintReadOnly, NotReplicated)
	bool bIsQuickSlotted = false;
	
	/** Used to track quick-slotted weapons currently in use. */
	UPROPERTY(BlueprintReadOnly)
	bool bIsUsed = false;
	
	/** Quick slot tag associated with this item when quick-slotted. */
	UPROPERTY(BlueprintReadOnly, NotReplicated)
	FGameplayTag QuickSlotTag = FGameplayTag();
	
	/** Returns whether this entry represents a valid item. */
	bool IsValid() const
	{
		return ItemID != 0;
	}
};

DECLARE_MULTICAST_DELEGATE_OneParam(FInventoryItemChangedSignature, const FRPGInventoryEntry& /*DirtyEntry*/);
DECLARE_MULTICAST_DELEGATE_OneParam(FInventoryItemRemovedSignature, const int64 /*RemovedItemID*/);
DECLARE_MULTICAST_DELEGATE_OneParam(FInventoryQuickSlotRelocatedSignature, const FRPGInventoryEntry& /*EntryToRelocate*/);
DECLARE_MULTICAST_DELEGATE_OneParam(FInventoryQuickSlotChangedSignature, const FRPGInventoryEntry& /*QuickSlotEntryToUpdate*/);
DECLARE_MULTICAST_DELEGATE_OneParam(FInventoryQuickSlotRemovedSignature, const int64 /*QuickSlotEntryIDToRemove*/);

USTRUCT()
struct FRPGInventoryList : public FFastArraySerializer
{
	GENERATED_BODY()

	/** Default constructor required by Unreal serialization. */
	FRPGInventoryList() : OwnerComponent(nullptr) {}
	
	/** Constructor that binds this list to its owning inventory component. */
	FRPGInventoryList(UInventoryComponent* InComponent) : OwnerComponent(InComponent) {}

	/** Adds an item to the list, optionally handling stacking and generation. */
	void AddItem(const FGameplayTag& ItemTag, int32 NumItems = 1);
	
	/** Removes a specified number of items from an entry. */
	void RemoveItem(const FRPGInventoryEntry& InventoryEntry, int32 NumItems = 1);
	
	/** Checks if the inventory contains at least NumItems of the given ItemID. */
	bool HasEnough(int64 ItemID, int32 NumItems) const;
	
	/** Generates a unique 64-bit ID for a new item. */
	int64 GenerateID();
	
	/** Sets the data table used for rolling stats. */
	void SetStats(UEquipmentStatEffects* InStats);
	
	/** Sets the data table used for rolling rarity. */
	void SetRarityTable(UDataTable* InRarityTable);
	
	/** Adds an already unequipped item back to the list cleanly. */
	void AddUnEquippedItem(UInventoryItem* Item);
	
	/** Gets the inventory entry currently using the specified quick slot tag. */
	FRPGInventoryEntry* GetAlreadyQuickSlottedEntry(const FGameplayTag& QuickSlotTag);
	
	/** Associates an inventory entry with a specific quick slot tag. */
	void AddEntryToQuickSlot(int64 ItemID, const FGameplayTag& QuickSlotTag);
	
	/** Clears a quick slot tag from the associated item. */
	void RemoveEntryFromQuickSlot(const int64 ItemID);

	/** Finds and returns a pointer to the entry with the given ID, or nullptr if not found. */
	FRPGInventoryEntry* FindEntryByID(int64 ItemID);

	// FFastArraySerializer Contract
	void PreReplicatedRemove(const TArrayView<int32>& RemovedIndices, int32 FinalSize);
	void PostReplicatedAdd(const TArrayView<int32>& AddedIndices, int32 FinalSize);
	void PostReplicatedChange(const TArrayView<int32>& ChangedIndices, int32 FinalSize);
		
	bool NetDeltaSerialize(FNetDeltaSerializeInfo& DeltaParms)
	{
		return FFastArraySerializer::FastArrayDeltaSerialize<FRPGInventoryEntry, FRPGInventoryList>(Entries, DeltaParms, *this);
	}

	/** Broadcast when a standard inventory entry changes. */
	FInventoryItemChangedSignature InventoryItemChangedDelegate;
	/** Broadcast when a standard inventory entry is removed. */
	FInventoryItemRemovedSignature InventoryItemRemovedDelegate;
	/** Broadcast when an entry is relocated across quick slots. */
	FInventoryQuickSlotRelocatedSignature QuickSlotItemRelocatedDelegate;
	/** Broadcast when a quick-slot entry changes. */
	FInventoryQuickSlotChangedSignature QuickSlotItemChangeDelegate;
	/** Broadcast when a quick-slot entry is removed. */
	FInventoryQuickSlotRemovedSignature QuickSlotItemRemovedDelegate;

private:

	friend class UInventoryComponent;

	/** Replicated fast-array storage for inventory entries. */
	UPROPERTY()
	TArray<FRPGInventoryEntry> Entries;

	/** Owning inventory component used for callbacks and authority checks. */
	UPROPERTY(NotReplicated)
	TObjectPtr<UInventoryComponent> OwnerComponent;

	/** Monotonic seed used to generate pseudo-unique item IDs. */
	UPROPERTY(NotReplicated)
	int64 LastAssignedID = 0;

	/** Weak ref to rolled stat configuration data. */
	UPROPERTY(NotReplicated)
	TWeakObjectPtr<UEquipmentStatEffects> WeakStatsData;

	/** Weak ref to rarity configuration table. */
	UPROPERTY(NotReplicated)
	TWeakObjectPtr<UDataTable> WeakRarityTable;

	/** Tries to find an existing stackable entry and increment its quantity. Returns true if stacked. */
	bool TryStackItem(const FGameplayTag& ItemTag, int32 NumItems);
	/** Marks an entry dirty and broadcasts a change event on authority. */
	void MarkEntryChanged(FRPGInventoryEntry& Entry);
	/** Handles relocation of any existing entry already assigned to a target quick slot. */
	void RelocateQuickSlotOccupant(FRPGInventoryEntry& EntryToAssign, const FGameplayTag& QuickSlotTag);

	/** Fills the equipment-specific fields of NewEntry (rarity, stats, abilities). */
	void RollEquipmentEntry(FRPGInventoryEntry& NewEntry, const FMasterItemDefinition& ItemDef);

	/** Marks an entry dirty and broadcasts it if running with authority. */
	void BroadcastNewEntry(FRPGInventoryEntry& NewEntry);

	/**
	 * Dispatches the appropriate delegate based on the entry's QuickSlot state and the operation type.
	 * @param Entry    The inventory entry involved in the change or removal.
	 * @param bChanged If true, broadcasts a "changed/updated" delegate; if false, broadcasts a "removed" delegate.
	 */
	void BroadcastEntryUpdate(const FRPGInventoryEntry& Entry, bool bChanged);

};

template<>
struct TStructOpsTypeTraits<FRPGInventoryList> : public TStructOpsTypeTraitsBase2<FRPGInventoryList>
{
	enum
	{
		WithNetDeltaSerializer = true,
	};
};

UCLASS(ClassGroup = (Custom), meta = (BlueprintSpawnableComponent))
class MAKHIA_API UInventoryComponent : public UActorComponent
{
	GENERATED_BODY()

public:

	// -------------------------------------------------------------------------
	// Initialization & Core
	// -------------------------------------------------------------------------

	/** Default constructor */
	UInventoryComponent();

	/** Replicates the component properties. */
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	// -------------------------------------------------------------------------
	// Delegates
	// -------------------------------------------------------------------------

	/** Broadcasts when an equipment item is used. */
	FEquipmentItemUsed EquipmentItemUsedDelegate;

	/** Broadcasts when an equipment item is unequipped. */
	FEquipmentItemUnequipped EquipmentItemUnequippedDelegate;

	// -------------------------------------------------------------------------
	// Replicated State
	// -------------------------------------------------------------------------

	/** Replicated list tracking all inventory entries safely. */
	UPROPERTY(Replicated)
	FRPGInventoryList InventoryList;

	// -------------------------------------------------------------------------
	// Inventory Operations
	// -------------------------------------------------------------------------

	/** Adds an item to the inventory. */
	UFUNCTION(BlueprintCallable, Category = "Inventory|Operations")
	void AddItem(const FGameplayTag& ItemTag, int32 NumItems = 1);

	/** Uses an item from the inventory. */
	UFUNCTION(BlueprintCallable, Category = "Inventory|Operations")
	void UseItem(int64 ItemID, int32 NumItems = 1);

	/** Adds an item entry that was unequipped back to the inventory properly. */
	void AddUnEquippedItemEntry(UInventoryItem* Item);

	// -------------------------------------------------------------------------
	// QuickSlot Management
	// -------------------------------------------------------------------------

	/** Adds an entry to a QuickSlot. */
	UFUNCTION(BlueprintCallable, Category = "Inventory|QuickSlot")
	void AddEntryToQuickSlot(int64 ItemID, const FGameplayTag& QuickSlotTag);
	
	/** Removes an entry from a QuickSlot. */
	UFUNCTION(BlueprintCallable, Category = "Inventory|QuickSlot")
	void RemoveEntryFromQuickSlot(int64 ItemID);

	// -------------------------------------------------------------------------
	// Lookups & Queries
	// -------------------------------------------------------------------------

	/** Retrieves the item definition using its tag. */
	UFUNCTION(BlueprintPure, Category = "Inventory|Queries")
	FMasterItemDefinition GetItemDefinitionByTag(const FGameplayTag& ItemTag) const;

	/** Returns a copy of the entry with the given ID. Check IsValid() on the result. */
	UFUNCTION(BlueprintPure, Category = "Inventory|Queries")
	FRPGInventoryEntry FindInventoryEntryByID(int64 ItemID);

	/** Retrieves all inventory entries. */
	TArray<FRPGInventoryEntry> GetInventoryEntries() const;

	// -------------------------------------------------------------------------
	// Preloading
	// -------------------------------------------------------------------------

	/**
	 * Preloads the assets of the weapon being quickslotted.
	 * Allows immediate use (e.g., sheathed attacks) without loading hitches.
	 */
	void PreloadItem(FRPGInventoryEntry* Entry);

	/** Removes an item's preloaded asset references. */
	void RemovePreloadedItemRef(int64 ItemID);
	
protected:

	virtual void BeginPlay() override;

	// -------------------------------------------------------------------------
	// Internal Actions
	// -------------------------------------------------------------------------

	/** Tries to use a consumable item and applies its effect if valid. */
	void TryUseConsumable(FRPGInventoryEntry* Entry, const FMasterItemDefinition& ItemDef, class UAbilitySystemComponent* OwnerASC, int32 NumItems);

	/** Tries to use an equipment item, broadcasting usage delegates. */
	void TryUseEquipment(FRPGInventoryEntry* Entry, const FMasterItemDefinition& ItemDef);
	
	/** Marks an equipped weapon entry as currently used and propagates list updates. */
	void MarkWeaponEntryUsed(FRPGInventoryEntry& Entry);

	/** Preloads all equipment actor assets for the given definition. */
	void PreloadEquipmentActors(const UEquipmentDefinition* EquipmentCDO, TArray<TSharedPtr<FStreamableHandle>>& Handles, FStreamableManager& Manager);

	/** Preloads all abilities specified in the effect package. */
	void PreloadAbilities(const FEquipmentEffectPackage& EffectPackage, TArray<TSharedPtr<FStreamableHandle>>& Handles, FStreamableManager& Manager);

	/** Preloads all passive stat effect classes. */
	void PreloadPassiveEffects(const FEquipmentEffectPackage& EffectPackage, TArray<TSharedPtr<FStreamableHandle>>& Handles, FStreamableManager& Manager);

private:

	// -------------------------------------------------------------------------
	// Configuration Data
	// -------------------------------------------------------------------------

	/** Stat effects configuration for rolled equipment passives. */
	UPROPERTY(EditDefaultsOnly, Category = "Custom Values|Stat Effects")
	TObjectPtr<UEquipmentStatEffects> StatEffectsData;

	/** Rarity table used to configure rolled equipment items. */
	UPROPERTY(EditDefaultsOnly, Category = "Custom Values|Rarity")
	TObjectPtr<UDataTable> RarityTable;

	/** Master tag-to-table definition mapping for items. */
	UPROPERTY(EditDefaultsOnly, Category = "Custom Values|Item Definitions")
	TObjectPtr<UItemTypesToTables> InventoryDefinitions;

	// -------------------------------------------------------------------------
	// RPCs
	// -------------------------------------------------------------------------

	/** Server RPC for adding items. */
	UFUNCTION(Server, Reliable)
	void ServerAddItem(const FGameplayTag& ItemTag, int32 NumItems);

	/** Server RPC for using items. */
	UFUNCTION(Server, Reliable, WithValidation)
	void ServerUseItem(int64 ItemID, int32 NumItems);
	bool ServerUseItem_Validate(int64 ItemID, int32 NumItems);

	// -------------------------------------------------------------------------
	// Internal State
	// -------------------------------------------------------------------------

	/** Maps item IDs to their asynchronously loaded asset handles. */
	TMap<int64, TArray<TSharedPtr<FStreamableHandle>>> PreloadedItemHandles;

};
