// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace RPGGameplayTags::Combat
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
}

namespace RPGGameplayTags::State::Movement
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Idle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Walking);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Sprinting);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchingIdle);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(CrouchingMoving);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Jumping);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Falling);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LandingInPlace);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(LandingMoving);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Dodging);
}

namespace RPGGameplayTags::State
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(OutOfStamina);
}

namespace RPGGameplayTags::Equip
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Category_Equipment);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Category_Weapon);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Category_Consumable);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ArmorSlot);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponSlot);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableQuickSlot1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableQuickSlot2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ConsumableQuickSlot3);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponQuickSlotCategory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponQuickSlot1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(WeaponQuickSlot2);
}

namespace RPGGameplayTags::Input
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Inventory);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(QuickSlot);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attacks);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Skill);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillSlot1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillSlot2);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(SkillSlot3);
}

namespace RPGGameplayTags::Event
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitScanStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(HitScanEnd);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ContinueComboStart);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(ContinueComboEnd);
}